"""empty message

Revision ID: 1aace09bd37a
Revises: 9ddaed88d85e
Create Date: 2021-06-03 11:01:44.259357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aace09bd37a'
down_revision = '9ddaed88d85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_URL')
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('_alembic_tmp_URL',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('shorturl', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('url_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['URL.id'], name='url_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
