"""empty message

Revision ID: 27666d2b0f7f
Revises: bffcab31c043
Create Date: 2021-06-04 08:25:47.483470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27666d2b0f7f'
down_revision = 'bffcab31c043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.drop_column('expiry')

    # ### end Alembic commands ###
