"""empty message

Revision ID: 341870ad21bf
Revises: e8d269d4785a
Create Date: 2021-06-03 11:12:46.928059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341870ad21bf'
down_revision = 'e8d269d4785a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
