"""empty message

Revision ID: 8993d2e29a25
Revises: 341870ad21bf
Create Date: 2021-06-03 15:57:42.028695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8993d2e29a25'
down_revision = '341870ad21bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=60), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
