"""empty message

Revision ID: 9ddaed88d85e
Revises: bbe89fe4dc77
Create Date: 2021-06-03 09:12:36.049620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddaed88d85e'
down_revision = 'bbe89fe4dc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('URL', 'URL', ['url_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('url_id')

    # ### end Alembic commands ###
