"""empty message

Revision ID: d7195d961d8d
Revises: 27666d2b0f7f
Create Date: 2021-06-04 08:33:43.752651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7195d961d8d'
down_revision = '27666d2b0f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.drop_column('expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('URL', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
